### ISSUE TITLE
application-testing 1차 검수

### ISSUE THREAD

**Issue by paikwiki** [laravelkr/docs#10]
@@ -30,7 +30,7 @@

Laravel provides a very fluent API for making HTTP requests to your application, examining the output, and even filling out forms. For example, take a look at the test defined below:

라라벨은 어플리케이션에 HTTP request-요청을 하고, 결과을 검사하고, 또한 form을 채우는 매우 다양한 사용이 가능한 API를 제공합니다. 다음에 정의된 테스트 예제를 살펴보겠습니다:
라라벨은 어플리케이션에 HTTP request-요청을 하고, 결과를 검사하고, 또한 form을 채우는 매우 다양한 사용이 가능한 API를 제공합니다. 다음에 정의된 테스트 예제를 살펴보겠습니다:

@@ -54,11 +54,11 @@ Laravel provides a very fluent API for making HTTP requests to your application,

The `visit` method makes a `GET` request into the application. The `see` method asserts that we should see the given text in the response returned by the application. The `dontSee` method asserts that the given text is not returned in the application response. This is the most basic application test available in Laravel.

`visit` 메소드는 어플리케이션에 `GET` request-요청을 만듭니다. `see` 메소드는 주어진 텍스트가 어플리케이션에서 반환된 reponse-응답에 있는지 확인 합니다. `dontSee` 메소드는 주어진 텍스트가 어플리케이션 response-응답으로 반환되지 않았다는 것을 확인합니다. 이것은 라라벨이 제공하는 가장 기본적인 어플리케이션 테스트입니다.
`visit` 메소드는 어플리케이션에 `GET` request-요청을 만듭니다. `see` 메소드는 어플리케이션에서 반환된 reponse-응답에 주어진 텍스트가 있는지 확인합니다. `dontSee` 메소드는 주어진 텍스트가 어플리케이션 response-응답으로 반환되지 않았다는 것을 확인합니다. 이것은 라라벨이 제공하는 가장 기본적인 어플리케이션 테스트입니다.

You may also use the `visitRoute` method to make a `GET` request via a named route:

또한 이름이 지정된 라우트에 대한 `GET` request를 만들기 위해서 `visitRoute` 메소드를 사용할 수도 있습니다:
또한 이름이 지정된 라우트에 대한 `GET` request를 만들기 위해서 `visitRoute` 메소드를 사용할 수 있습니다:

@@ -78,13 +78,13 @@ Of course, you can do much more than simply assert that text appears in a given

In this test, we will make a request to the application, "click" a link in the returned response, and then assert that we landed on a given URI. For example, let's assume there is a link in our response that has a text value of "About Us":

이 테스트에서는 어플리케이션에 요청을 보내고, 응답으로 돌아온 링크를 "클릭"하여, 특정 URI에 이동된것을 확인할 것입니다. 예를 들어 응답으로 "About Us"이라는 텍스트 값을 가진 링크가 왔다고 가정해봅시다:
이 테스트에서는 어플리케이션에 요청을 보내고, 응답으로 돌아온 링크를 "클릭"하여, 주어진 URI로 이동하도록 할 것입니다. 예를 들어 응답으로 "About Us"이라는 텍스트 값을 가진 링크가 왔다고 가정해봅시다:

```
<a href="/about-us">About Us</a>
```

Now, let's write a test that clicks the link and asserts the user lands on the correct page:

이제 링크를 클릭하고 사용자가 알맞은 페이지로 이동한다고 확인하는 테스트를 작성해 봅시다:
이제 링크를 클릭해 사용자가 알맞은 페이지로 이동했는지 확인하는 테스트를 작성해 봅시다:

@@ -95,7 +95,7 @@ Now, let's write a test that clicks the link and asserts the user lands on the c

You may also check that the user has arrived at the correct named route using the `seeRouteIs` method:

또한 `seeRouteIs` 메소드를 사용하여 사용자가 이름이 지정된 라우트에 도착했는지 확인 할 수도 있습니다.
또한 `seeRouteIs` 메소드를 사용하여 사용자가 이름이 지정된 라우트에 도착했는지 확인할 수 있습니다.

```
->seeRouteIs('profile', ['user' => 1]);
```

@@ -105,7 +105,7 @@ You may also check that the user has arrived at the correct named route using th

Laravel also provides several methods for testing forms. The `type`, `select`, `check`, `attach`, and `press` methods allow you to interact with all of your form's inputs. For example, let's imagine this form exists on the application's registration page:

라라벨은 또한 form을 테스트하는 여러 메소드들을 제공합니다. `type`, `select`, `check`, `attach`, 그리고 `press` 메소드들은 form의 모든 input들과 상호작용할 수 있도록 해줍니다. 예를 들어 이 form이 어플리케이션의 등록 페이지에 존재한다고 가정해보겠습니다:
라라벨은 또한 form을 테스트하는 여러 메소드들을 제공합니다. `type`, `select`, `check`, `attach`, 그리고 `press` 메소드는 form의 모든 input들과 상호작용할 수 있도록 해줍니다. 예를 들어 이 form이 어플리케이션의 등록 페이지에 존재한다고 가정해보겠습니다:

```
<form action="/register" method="POST">
    {{ csrf_field() }}
```

@@ -138,7 +138,7 @@ We can write a test to complete this form and inspect the result:

Of course, if your form contains other inputs such as radio buttons or drop-down boxes, you may easily fill out those types of fields as well. Here is a list of each form manipulation method:

물론 form이 라디오 버튼이나 드롭다운 박스와 같은 다른 input을 가지고 있다면 이런 종류의 필드들도 손쉽게 채울 수 있습니다. 다음은 각각의 form을 조작하는 메소드 목록입니다:
물론 form이 라디오 버튼이나 드롭다운 박스와 같은 다른 input을 가지고 있다면 이런 종류의 필드도 손쉽게 채울 수 있습니다. 다음은 각각의 form을 조작하는 메소드 목록입니다:

@@ -152,9 +152,9 @@ Method  | Description
메소드  | 설명
------------- | -------------
`$this->type($text, $elementName)`  |  주어진 필드에 텍스트를 "채워넣음"
`$this->select($value, $elementName)`  |  라디오 버튼 또는 드랍다운 필드를 "선택"
`$this->select($value, $elementName)`  |  라디오 버튼 또는 드롭다운 필드를 "선택"

@@ -202,7 +202,7 @@ Laravel also provides several helpers for testing JSON APIs and their responses.

> {tip} The `seeJson` method converts the given array into JSON, and then verifies that the JSON fragment occurs **anywhere** within the entire JSON response returned by the application. So, if there are other properties in the JSON response, this test will still pass as long as the given fragment is present.
> 
> {팁} `seeJson` 메소드는 주어진 배열을 JSON으로 변환하고 변환된 JSON이 어플리케이션이 반환하는 JSON 응답 중 **어느 한곳에** 존재하는 것을 확인합니다. 따라서 JSON response-응답이 다른 속성을 가지고 있어도 특정 부분이 있기만 하면 테스트는 통과할 것입니다.
> {팁} `seeJson` 메소드는 주어진 배열을 JSON으로 변환하고 변환된 JSON이 어플리케이션이 반환하는 JSON 응답 중 **어느 한 곳에** 존재하는 것을 확인합니다. 따라서 JSON response-응답이 다른 속성을 가지고 있어도 특정 부분이 있기만 하면 테스트는 통과할 것입니다.

@@ -210,7 +210,7 @@ Laravel also provides several helpers for testing JSON APIs and their responses.

If you would like to verify that the given array is an **exact** match for the JSON returned by the application, you should use the `seeJsonEquals` method:

주어진 배열이 반환된 JSON과 **정확히** 일치하는지 확인하고자 한다면, `seeJsonEquals` 메소드를 사용하면됩니다:
주어진 배열이 반환된 JSON과 **정확히** 일치하는지 확인하고자 한다면, `seeJsonEquals` 메소드를 사용하면 됩니다:

@@ -236,7 +236,7 @@ If you would like to verify that the given array is an **exact** match for the J

It is also possible to verify that a JSON response adheres to a specific structure. In this scenario, you should use the `seeJsonStructure` method and pass it your expected JSON structure:

JSON 응답이 지정한 구조에 부합하는지 확인하는 것도 가능합니다. 이 시나리오에서  `seeJsonStructure` 메소드를 사용하고 기대되는 JSON 구조를 전달해야 합니다:
JSON 응답이 지정한 구조에 부합하는지 확인하는 것도 가능합니다. 이 시나리오에서는 `seeJsonStructure` 메소드를 사용할 것이며, 기대되는 JSON 구조를 전달해야 합니다:

@@ -261,11 +261,11 @@ JSON 응답이 지정한 구조에 부합하는지 확인하는 것도 가능합

The above example illustrates an expectation of receiving a `name` and a nested `pet` object with its own `name` and `age`. `seeJsonStructure` will not fail if additional keys are present in the response. For example, the test would still pass if the `pet` had a `weight` attribute.

위의 예제에서는 `name` 과 중첩된 `name` 과 `age`를 가지는 `pet` 객체를 전달 받는 것을 기대하는 것입니다. 응답에 추가적인 키가 존재하는 것은 `seeJsonStructure` 에서는 실패로 간주되지 않습니다. 예를 들어 `pet`에 `weight` 속성을 가지고 있다고 해도 테스트는 여전히 통과 할 것입니다.
위의 예제는 "`name`" 과 "중첩된 `name` 과 `age`를 가지는 `pet` 객체"를 반환할 것이라고 예상하고 있습니다. 응답에 추가적인 키가 존재한다 해도 `seeJsonStructure` 에서는 실패로 간주되지 않습니다. 예를 들어 `pet`에 `weight` 속성을 가지고 있다고 해도 테스트는 여전히 통과할 것입니다.

You may use the `*` to assert that the returned JSON structure has a list where each list item contains at least the attributes found in the set of values:

반환된 JSON 구조가 각 목록 아이템 값의 세트에서 적어도 주어진 속성을 포함하는 리스트를 가지고 있는지 확인할 수 있도록 `*`를 사용할 수 있습니다:
반환된 JSON 구조가 각 목록 아이템 값의 세트에서 주어진 속성을 반드시 포함하는 리스트를 가지고 있는지 확인하기 위해 `*`를 사용할 수 있습니다:

@@ -290,7 +290,7 @@ You may use the `*` to assert that the returned JSON structure has a list where

You may also nest the `*` notation. In this case, we will assert that each user in the JSON response contains a given set of attributes and that each pet on each user also contains a given set of attributes:

`*` 표기는 중첩할 수도 있습니다. 다음 예제의 경우 JSON response 는 각각의 사용자가 주어진 속성들을 가지고 사용자의 pet들은 중첩되어 주어진 속성들을 가지고 있는지 확인할 수 있습니다:
`*` 표기는 중첩할 수도 있습니다. 다음 예제의 경우 JSON response는 각각의 사용자가 주어진 속성들을 가지고 사용자의 pet들은 중첩되어 주어진 속성들을 가지고 있는지 확인할 수 있습니다:

@@ -309,7 +309,7 @@ You may also nest the `*` notation. In this case, we will assert that each user

Laravel provides several helpers for working with the session during testing. First, you may set the session data to a given array using the `withSession` method. This is useful for loading the session with data before issuing a request to your application:

라라벨은 테스팅 중 세션 작업을 하는 데 필요한 여러 헬퍼들을 제공합니다. 먼저, `withSession` 메소드를 이용하여 주어진 배열을 세션 데이터로 설정 할 수 있습니다. 이것은 어플리케이션에 response-응답을 전달하기 전에 데이터를 세션에 로드하는 경우에 유용합니다:
라라벨은 테스팅 중 세션 작업을 하는 데 필요한 여러 헬퍼들을 제공합니다. 먼저, `withSession` 메소드를 이용하여 주어진 배열을 세션 데이터로 설정할 수 있습니다. 이것은 어플리케이션에 response-응답을 전달하기 전에 데이터를 세션에 로드하는 경우에 유용합니다:

@@ -343,17 +343,17 @@ Of course, one common use of the session is for maintaining state for the authen

You may also specify which guard should be used to authenticate the given user by passing the guard name as the second argument to the `actingAs` method:

또한 `actingAs` 메소드의 두번째 인자로 주어진 사용자에 대한 인증에 어떤 guard 를 사용해야 하는지 지정하도록 guard 이름을 전달 할 수도 있습니다:
또한 `actingAs` 메소드의 두 번째 인자로 주어진 사용자에 대한 인증에 어떤 guard를 사용해야 하는지 지정하도록 guard 이름을 전달 할 수도 있습니다:

When testing your application, you may find it convenient to disable [middleware](/docs/{{version}}/middleware) for some of your tests. This will allow you to test your routes and controller in isolation from any middleware concerns. Laravel includes a simple `WithoutMiddleware` trait that you can use to automatically disable all middleware for the test class:

어플리케이션을 테스트할 때 몇몇 테스트에서 [미들웨어](/docs/{{version}}/middleware)를 비활성화 하는 편리한 방법을 원할 수도 있습니다.
어플리케이션을 테스트할 때 일부 테스트에서 [미들웨어](/docs/{{version}}/middleware)를 비활성화 하는 편리한 방법을 원할 수도 있습니다.

@@ -396,7 +396,7 @@ If you would like to only disable middleware for a few test methods, you may cal

If you would like to make a custom HTTP request into your application and get the full `Illuminate\Http\Response` object, you may use the `call` method:

어플리케이션에 사용자 정의 HTTP request-요청을 하고 `Illuminate\Http\Response` 객체 전체를 가지고자 한다면 `call` 메소드를 이용하면 됩니다:
어플리케이션에 사용자 정의 HTTP request-요청을 하고 `Illuminate\Http\Response` 객체 전체를 가져오려면 `call` 메소드를 이용하면 됩니다:

**Comment by findstar** [comment]
검수 적용하여 수정하였습니다.
