### ISSUE TITLE
5.8 번역

### ISSUE THREAD

**Issue by kkame** [laravelkr/docs#105]
## 번역 기여자 모집

- 모집마감 : 3월  7일
- 번역마감 : 3월 24일

- 지원방법 : 하단에 아래의 양식으로 댓글을 남겨주세요

```
라라벨 경험 :  O or X
번역 경험: O or X
맡고 싶은 챕터(파일기준): ~~~.md
```

## 번역 방식
- 5.7의 번역 문서를 기준으로 5.8의 변경된 내역을 업데이트 하면 됩니다
- 따라서 문서 전체를 다 번역하실 필요가 없으며 (오히려 새로 번역하시면 기존의 문서와 표현이 달라지게됩니다) 아주 뛰어난 영어능력을 필요로 하지는 않습니다
- 준비가 완료되면 pre-kr-5.8 브랜치에서 작업을 하게 됩니다
- 모집이 종료되면 5.8 마일스톤 및 작업할당 분량에 대해 개별 이슈 등록을 해드리며 각자의 레포에서 작업하신 이후에 pr을 통해서 번역본을 전달 받습니다
- 관리자의 최종 문장 감수 이후에 kr-5.8 브랜치에 머지됩니다

## 오픈일정
상단의 완료된 번역은 관리자의 편집을 거쳐 4월1일 이전에 사이트에 공개됩니다

## 기여에 대한 보상
- 번역에 기여해주신 분들은 해당하는 문서의 하단에 기여자의 깃허브 계정이 노출됩니다

## 번역 리스트
- [x] ~api-authentication.md~ @kwonmory 
- [x] ~artisan.md~ @inyoungk 
- [x] ~authentication.md~ @kwonmory 
- [x] ~authorization.md~ @kwonmory 
- [x] ~billing.md~ @epicsagas 
- [x] ~blade.md~ @natz92 
- [x] ~braintree.md~ @kkame 
- [x] ~broadcasting.md~ @kkame 
- [x] ~cache.md~ @kkame 
- [x] ~collections.md~ @ukits 
- [x] configuration.md
- [x] ~console-tests.md~ @lastgleam 
- [x] container.md
- [x] contracts.md
- [x] contributions.md
- [x] ~controllers.md~ @inyoungk 
- [x] csrf.md
- [x] ~database-testing.md~ @lastgleam 
- [x] database.md
- [x] deployment.md
- [x] documentation.md
- [x] dusk.md
- [x] ~eloquent-collections.md~ @whdckszxxx 
- [x] eloquent-mutators.md
- [x] eloquent-relationships.md @natz92 
- [x] eloquent-resources.md
- [x] eloquent-serialization.md @lastgleam 
- [x] ~eloquent.md~ @getsolaris 
- [x] encryption.md
- [x] ~envoy.md~ @natz92 
- [x] errors.md
- [x] events.md
- [x] facades.md
- [x] filesystem.md
- [x] frontend.md
- [x] hashing.md
- [x] helpers.md
- [x] homestead.md
- [x] horizon.md
- [x] ~http-tests.md~ @natz92 
- [x] installation.md
- [X] license.md
- [x] lifecycle.md
- [x] localization.md
- [x] logging.md
- [x] mail.md
- [x] middleware.md
- [x] migrations.md
- [x] mix.md
- [x] ~mocking.md~ @lastgleam 
- [x] notifications.md
- [x] packages.md
- [x] pagination.md
- [x] passport.md
- [x] passwords.md
- [x] providers.md
- [x] queries.md
- [x] ~queues.md~ @strawoo 
- [x] readme.md
- [x] redirects.md
- [x] redis.md
- [x] releases.md
- [x] ~requests.md~ @SilNex 
- [x] responses.md
- [x] ~routing.md~ @findstar 
- [x] scheduling.md
- [x] scout.md
- [x] seeding.md
- [x] session.md
- [x] socialite.md
- [x] structure.md
- [x] telescope.md
- [x] ~testing.md~ @lastgleam 
- [x] ~upgrade.md~ @kkame 
- [x] urls.md
- [x] valet.md
- [x] validation.md
- [x] verification.md
- [x] views.md

**Comment by findstar** [comment]
- 라라벨 경험 :  O
- 번역 경험: O
- 맡고 싶은 챕터(파일기준): routing.md

**Comment by epicsagas** [comment]
라라벨 경험 : O
번역 경험: O
맡고 싶은 챕터(파일기준): billing.md

**Comment by kwonmory** [comment]
- 라라벨 경험 : O
- 번역 경험 : X
- 맡고 싶은 챕터(파일기준): authorization.md 또는 authentication.md

**Comment by natz92** [comment]
- 라라벨 경험 : O
- 번역 경험 : O
- 맡고 싶은 챕터(파일기준): blade.md / envoy.md / http-tests.md

**Comment by getsolaris** [comment]
- 라라벨 경험 : O
- 번역 경험 : X
- 맡고 싶은 챕터(파일기준): eloquent.md

**Comment by chanzxxx** [comment]
라라벨경험: O
번역경험: O
맡고싶은 챕터: eloquent-collections.md

**Comment by silnex** [comment]
라라벨경험: O
번역경험: X
맡고싶은 챕터: requests.md

**Comment by ukits** [comment]
라라벨 경험: O
번역 경험: X
맡고 싶은 챕터: collections.md

**Comment by inyoungk** [comment]
라라벨경험: O
번역경험: X
맡고싶은 챕터: artisan.md, controllers.md

**Comment by coreajk** [comment]
라라벨경험：O
번역경험 : X
맡고싶은 챕터: 
braintree.md
broadcasting.md
cache.md

**Comment by strawoo** [comment]
라라벨경험: O
번역경험: X
맡고싶은 챕터: 
queues.md
providers.md 추가로 할게요!

**Comment by lastgleam** [comment]
라라벨경험：O
번역경험 : O
맡고싶은 챕터:
testing.md
console-tests.md
database-testing.md
mocking.md

**Comment by strawoo** [comment]
providers.md 추가로 할게요!

**Comment by kwonmory** [comment]
라라벨 경험 : O
번역 경험 : X
**추가로** 맡고 싶은 챕터(파일기준): 
- api-authentication.md
- authentication.md

> 모집 기간이 지난거 같긴한데 아직 자리가 많이 있는 것 같아서 추가로 신청 가능하면 아래 부분도 하고싶습니다. 
auth 한꺼번에 하는 것도 좋을 것 같아서요~ 😄

**Comment by kkame** [comment]
## 번역자 모집 마감 안내
현재까지 코멘트해준 분들을 기준으로 5.8 번역에 대한 번역자 모집을 마감하겠습니다.

## 번역 방식 안내 
- laravelkr/docs 레포지터리를 자신의 깃허브로 포크 합니다.
- 관리자가 생성해둔 kr 폴더내의 자신의 파일에 5.8의 번역내용을 업데이트 합니다
  - 해당 폴더에는 5.7의 기존 번역 내용이 들어있습니다. 편의에 따라 삭제 후 번역 또는 변경부분만 업데이트 후 번역 하시면 됩니다
  - kr 폴더 내의 파일만 수정하셔야 합니다.
  - 번역도중에 원문이 업데이트 되더라도 번역의 싱크를 위해 별도 업데이트를 하지 않습니다
- 번역이 완료된 이후 커밋하여 PR을 합니다
- 관리자가 확인후 merge 합니다
  - merge 된 이후라도 번역의 수정 PR은 언제라도 추가 가능하니 번역문을 수정하고 싶으신 경우 추가 PR을 합니다

## 브랜치 생성 안내
- 3월9일 12~2시 사이에 pre-kr-5.8 브랜치를 laravelkr/docs 레포지터리에 생성

## 참조사항
- [위키](https://github.com/laravelkr/docs/wiki) 에서 번역에 필요한 내용을 확인하시기 바랍니다
- 해당 위키로 부족한 부분은 현재의 이슈에 관련하여 알려주시면 업데이트 하도록 하겠습니다

## 추가적인 질문 안내
- 현재의 이슈에 궁금하신 사항을 추가해주시면됩니다

---- 
번역 시작하신 분들의 체크를 위해 이 코멘트를 확인하신 분들은 이 코멘트에 리액션을 추가해주시면 감사하겠습니다

**Comment by kkame** [comment]
### 작업방식 팁 안내
 vscode 에서 gitlens 플러그인 설치한 이후 pre-kr-5.7의 브랜치와 pre-kr-5.8의 브랜치를 비교해보시면
변경/추가된 파일과 변경 내역이 보입니다.  
이걸 참조하셔서 작업하시면 비교하시기가 조금 더 수월 할 것 같습니다
thianks to @natz92 

그 외에 작업하시면서 궁금한 사항은 댓글 부탁드립니다.
만약 깃허브로 문의하시기가 곤란한 내용이 있으시다면
모던PHP User Group 슬랙의 라라벨 채널 / 라라벨 오픈톡방에서 운영진을 찾으시면 됩니다

**Comment by kkame** [comment]
안녕하세요
어느던 번역을 시작한지 일주일이 지났네요
생각보다 변경사항이 많지 않은 파일을 담당하신 분은 이미 작업을 완료 하신 분도 있고
변경사항이 많은 분은 아직 진행중이신 분들도 있으신 것 같네요
혹시 번역 분량에 조정이 필요하다거나 다른 협의 사항이 필요하신 분들은 연락주세요

@epicsagas, @kwonmory, @natz92, @getsolaris, @whdckszxxx, @SilNex, @ukits, @inyoungk, @pursang81, @strawoo, @lastgleam

**Comment by natz92** [comment]
```
- envoy.md 완료
- http-tests.md 변동사항 없음
- blade.md 변동사항 없음
```
 eloquent-relationships 추가로 번역하겠습니다.

**Comment by lastgleam** [comment]
> 안녕하세요
> 어느던 번역을 시작한지 일주일이 지났네요
> 생각보다 변경사항이 많지 않은 파일을 담당하신 분은 이미 작업을 완료 하신 분도 있고
> 변경사항이 많은 분은 아직 진행중이신 분들도 있으신 것 같네요
> 혹시 번역 분량에 조정이 필요하다거나 다른 협의 사항이 필요하신 분들은 연락주세요
> 
> @epicsagas, @kwonmory, @natz92, @getsolaris, @whdckszxxx, @SilNex, @ukits, @inyoungk, @pursang81, @strawoo, @lastgleam

@kkame `eloquent-serialization` 추가로 하겠습니다.

**Comment by lastgleam** [comment]
@kkame `eloquent-serialization`도 5.7과 비교해서 바뀐 부분이 없었습니다.

**Comment by chanzxxx** [comment]
번역하려고 했던 `eloquent-collections` 문서에 변동사항이 없습니다. 추가로 `dusk` 문서도 확인해봤는데 여기도 바뀐부분이 없네요.

`documentation.md` 파일의 링크 경로 수정된 부분 발견하여 이부분은 따로 pr 등록했습니다. #123

**Comment by natz92** [comment]
`eloquent-relationships` 번역 및 pr 등록 #151

**Comment by strawoo** [comment]
`queues.md` 반영했습니다. 추가된 번역내용은 없으나 문서에서 변경된 내용을 반영했습니다.
#152

**Comment by getsolaris** [comment]
`eloquent` PR 등록 했습니다. #154

**Comment by kkame** [comment]
금일부로 나눠서 번역하던 작업은 모두 종료하도록 하겠습니다.
다들 바쁘신 와중에 번역까지 해주시느라 너무 수고많으셨습니다.
5.8 최종번역완료분은 이번주 주말중으로 업데이트 될 예정이며
다시 한번 참여해주신 모든 분들에게 감사드립니다.
