### ISSUE TITLE
cache 1차 검수

### ISSUE THREAD

**Issue by paikwiki** [laravelkr/docs#11]
@@ -2,9 +2,9 @@

```
- [Configuration](#configuration)
    - [Driver Prerequisites](#driver-prerequisites)
    - [드라이버 사전 준비사항](#driver-prerequisites)
- [설정하기](#configuration)
```

> "`- [설정하기](#configuration)`가 2행 위로 올라가야 합니다" - @chpaik

@@ -38,11 +38,11 @@

Laravel provides an expressive, unified API for various caching backends. The cache configuration is located at `config/cache.php`. In this file you may specify which cache driver you would like used by default throughout your application.

라라벨은 다양한 캐시 시스템을 위해서 풍부한 표현이 가능한, 통일된 API를 제공합니다. 캐시 설정은 `config/cache.php` 파일에 있습니다. 이 파일에서 전체 응용프로그램에서 기본적으로 사용하는 캐시 드라이버를 지정할 수 있습니다.
라라벨은 다양한 캐시 시스템을 위해서 풍부한 표현이 가능한 통합 API를 제공합니다. 캐시 설정은 `config/cache.php` 파일에 있습니다. 이 파일에 전체 어플리케이션에서 기본적으로 사용할 캐시 드라이버를 지정할 수 있습니다.

@@ -82,7 +82,7 @@ Memcached 드라이버를 사용하려면 [Memcached PECL 패키지](http://pecl

You may also set the `host` option to a UNIX socket path. If you do this, the `port` option should be set to `0`:

또한 `host` 옵션으로 UNIX 소켓을 설정할 수도 있습니다. 이 경우 `port` 옵션은 `0` 으로 구성해야만 합니다. 
또한 `host` 옵션으로 UNIX 소켓을 설정할 수 있습니다. 이 경우 `port` 옵션은 `0` 으로 구성해야 합니다.

@@ -97,11 +97,11 @@ You may also set the `host` option to a UNIX socket path. If you do this, the `p

Before using a Redis cache with Laravel, you will need to install the `predis/predis` package (~1.0) via Composer.

라라벨에서 Redis 캐스를 사용하기 전에, 컴포저를 통해서 `predis/predis` 패키지(~1.0)를 설치해야만 합니다. 
라라벨에서 Redis 캐시를 사용하기 전에, 컴포저를 통해서 `predis/predis` 패키지(~1.0)를 설치해야 합니다.

@@ -113,7 +113,7 @@ Redis 설정과 관련된 보다 자세한 사항은 [라라벨 Redis 문서](/d

The `Illuminate\Contracts\Cache\Factory` and `Illuminate\Contracts\Cache\Repository` [contracts](/docs/{{version}}/contracts) provide access to Laravel's cache services. The `Factory` contract provides access to all cache drivers defined for your application. The `Repository` contract is typically an implementation of the default cache driver for your application as specified by your `cache` configuration file.

`Repository` 는 일반적으로 `cache` 설정 파일에서 기본으로 설정된 캐시 드라이버의 구현체에 입니다. 
`Repository` 는 일반적으로 `cache` 설정 파일에서 기본으로 설정된 캐시 드라이버의 구현체입니다.

@@ -145,7 +145,7 @@ However, you may also use the `Cache` facade, which is what we will use througho

Using the `Cache` facade, you may access various cache stores via the `store` method.

`Cache` 파사드를 사용하면서 `store` 메소드를 통해서 여러개의 캐시 Store 에 엑세스 할 수 있습니다.
`Cache` 파사드를 사용하면서 `store` 메소드를 통해서 여러 개의 캐시 Store 에 엑세스 할 수 있습니다.

@@ -157,7 +157,7 @@ Using the `Cache` facade, you may access various cache stores via the `store` me

The `get` method on the `Cache` facade is used to retrieve items from the cache. If the item does not exist in the cache, `null` will be returned.

`Cache` 파사드에서 `get` 메소드를 사용하여 캐시에 들어 있는 아이템을 찾을 수 있습니다. 아이템이 캐시에 들어 있지 않다면, `null` 이 반환될 것입니다.
`Cache` 파사드에서 `get` 메소드를 사용하여 캐시에 들어 있는 아이템을 찾을 수 있습니다. 아이템이 캐시에 없다면, `null` 이 반환될 것입니다.

@@ -166,7 +166,7 @@ The `get` method on the `Cache` facade is used to retrieve items from the cache.

You may even pass a `Closure` as the default value. The result of the `Closure` will be returned if the specified item does not exist in the cache. Passing a Closure allows you to defer the retrieval of default values from a database or other external service:

기본값을 `클로저`로 전달 할 수도 있습니다. 캐시에 아이템이 존재하지 않을 경우에 `클로저`의 반환값이 결과값이 됩니다. 클로저를 전달 한다는 것은 데이터베이스와 외부 서비스로부터 기본값을 획득할 수 있게 해줍니다. 
기본값을 `클로저`로 전달할 수도 있습니다. 캐시에 지정한 아이템이 존재하지 않을 경우에 `클로저`의 반환값이 결과값이 됩니다. 클로저를 전달하면 데이터베이스와 외부 서비스로부터 기본값을 획득할 수 있습니다.

@@ -177,18 +177,18 @@ You may even pass a `Closure` as the default value. The result of the `Closure` 

The `has` method may be used to determine if an item exists in the cache:

`has` 메소드는 캐시에서 아이템이 존재하는지 확인하느데 사용됩니다. 
`has` 메소드는 캐시에 아이템이 존재하는지 확인하는데 사용됩니다.

```
#### Incrementing / Decrementing Values
#### 증가 / 감소
#### 값 증가 또는 감소시키기
```

The `increment` and `decrement` methods may be used to adjust the value of integer items in the cache. Both of these methods accept an optional second argument indicating the amount by which to increment or decrement the item's value:

`increment` 와 `decrement` 메소드는 캐스에 들어 있는 아이템의 정수 값을 변경하는데 사용됩니다. 두 메소드는 모두 해당 아이템의 값을 얼마나 증가 또는 감소 시킬지 결정하는 두번째 인자를 선택적으로 전달 할 수 있습니다. 
`increment` 와 `decrement` 메소드는 캐시에 들어 있는 정수형 아이템의 값을 변경하는데 사용합니다. 두 메소드는 모두 해당 아이템의 값을 얼마나 증가 또는 감소 시킬지 결정하는 두 번째 인자를 선택적으로 전달할 수 있습니다.

@@ -200,7 +200,7 @@ The `increment` and `decrement` methods may be used to adjust the value of integ

Sometimes you may wish to retrieve an item from the cache, but also store a default value if the requested item doesn't exist. For example, you may wish to retrieve all users from the cache or, if they don't exist, retrieve them from the database and add them to the cache. You may do this using the `Cache::remember` method:

때로는 캐시로 부터 아이템을 찾는것 뿐만 아니라, 아이템이 존재하지 않는 경우에 기본값을 지정하고자 할 수도 있습니다. 예를 들어 캐시에서 모든 사용자를 찾고자 하는데, 값이 존재하지 않는 경우, 데이터베이스로부터 정보를 획득하여 캐시에 추가하고자 할 수도 있습니다. 이 경우에 `Cache::remember` 메소드를 사용하면 됩니다. 
때로는 캐시로부터 아이템을 찾는 것 뿐만 아니라, 찾으려는 아이템이 존재하지 않는 경우 기본값을 저장하고자 할 수도 있습니다. 예를 들어 캐시에서 모든 사용자를 찾으려 할 때 아무 것도 없다면, 데이터베이스로부터 정보를 획득하여 캐시에 추가하고자 할 수도 있습니다. 이 경우에 `Cache::remember` 메소드를 사용합니다.

@@ -208,14 +208,14 @@ Sometimes you may wish to retrieve an item from the cache, but also store a defa

If the item does not exist in the cache, the `Closure` passed to the `remember` method will be executed and its result will be placed in the cache.

캐시에서 아이템이 존재하지 않는 경우에, `remember` 메소드에 전달된 `클로저` 가 실행되어 캐시에 값을 저장하게 됩니다.
캐시에 아이템이 존재하지 않는 경우, `remember` 메소드에 전달된 `클로저` 가 실행되어 캐시에 값을 저장하게 됩니다.

@@ -225,24 +225,24 @@ If you need to retrieve an item from the cache and then delete the item, you may

You may use the `put` method on the `Cache` facade to store items in the cache. When you place an item in the cache, you need to specify the number of minutes for which the value should be cached:

`Cache` 파사드의 `put` 메소드를 사용하여 캐시에 아이템을 저장 할 수 있습니다. 캐시에 아이템을 저장할 때에는, 몇분 동안 저장 되어야 할지를 지정해야합니다.
`Cache` 파사드의 `put` 메소드를 사용하여 캐시에 아이템을 저장할 수 있습니다. 캐시에 아이템을 저장할 때에는, 몇 분 동안 저장해야 할지 지정해야 합니다.

```
Cache::put('key', 'value', $minutes);
```

Instead of passing the number of minutes as an integer, you may also pass a `DateTime` instance representing the expiration time of the cached item:

몇분동안 저장되어야 할지 정수형의 숫자를 전달하는 대신에, 캐시가 유지되는 유효 기간을 나타내는 `DateTime` 인스턴스를 전달할 수도 있습니다. 
몇 분동안 저장해야 할지 정수형의 숫자를 전달하는 대신에, 캐시된 아이템의 유효 기간을 나타내는 `DateTime` 인스턴스를 전달할 수 있습니다.
#### 존재하지 않으면 저장하기

The `add` method will only add the item to the cache if it does not already exist in the cache store.

`add` 메소드는 캐시에 아이템이 이미 존재하지 않는 경우에만 아이템을 저장할 것입니다.
`add` 메소드는 캐시에 아이템이 이미 존재하지 않는 경우에만 아이템을 저장합니다.

@@ -251,13 +251,13 @@ The `add` method will only add the item to the cache if it does not already exis

> {tip} If you are using the Memcached driver, items that are stored "forever" may be removed when the cache reaches its size limit.
> 
> {tip} 만약 Memcached 드라이버를 사용중이라면, "영구적으로" 저장된 아이템들은 캐시의 사이즈 제한에 도달한 경우 제거될 것입니다. 
> {tip} 만약 Memcached 드라이버를 사용중이라면, 캐시의 사이즈 제한에 도달한 경우 "영구적으로" 저장된 아이템들은 제거될 것입니다.

@@ -265,19 +265,19 @@ The `forever` method may be used to store an item in the cache permanently. Sinc

You may remove items from the cache using the `forget` method:

`forget` 메소드를 사용하여 캐시에서 아이템을 삭제 할 수 있습니다:
`forget` 메소드를 사용하여 캐시에서 아이템을 삭제할 수 있습니다:

> {note} Flushing the cache does not respect the cache prefix and will remove all entries from the cache. Consider this carefully when clearing a cache which is shared by other applications.
> 
> {note} 모든 캐시를 비우는 것은 캐시에서 모든 항목이 제거된다는 것을 의미합니다. 어플리케이션의 다른 부분에서 공유하는 캐시를 제거 할 때에 주의하십시오.
> {note} 모든 캐시를 비우는 것은 캐시에서 모든 항목이 제거된다는 것을 의미합니다. 어플리케이션의 다른 부분에서 공유하는 캐시를 제거할 때에 주의하십시오.

@@ -292,7 +292,7 @@ You may clear the entire cache using the `flush` method:

Cache tags allow you to tag related items in the cache and then flush all cached values that have been assigned a given tag. You may access a tagged cache by passing in an ordered array of tag names. For example, let's access a tagged cache and `put` value in the cache:

캐시 태그는 캐시에 있는 관련된 아이템들을 태그 할 수 있도록 해주고, 주어진 태그가 지정된 전체 캐시 항목들을 삭제 할 수도 있게 해줍니다. 여러분은 순서대로 태그 이름의 배열을 전달하여 태그가 추가된 캐시 아이템에 엑세스 할 수 있습니다. 예를 들어 태그가 지정된 캐시에 엑세스하여, 값을 `저장(put)` 해 보겠습니다. 
캐시 태그는 캐시에 있는 관련된 아이템들을 태그할 수 있도록 해주고, 주어진 태그가 지정된 전체 캐시 항목을 삭제할 수도 있게 해줍니다. 여러분은 순서대로 태그 이름의 배열을 전달하여 태그가 추가된 캐시 아이템에 엑세스할 수 있습니다. 예를 들어, 태그가 지정된 캐시에 엑세스하여, 값을 `저장(put)` 해 보겠습니다.

@@ -316,13 +316,13 @@ To retrieve a tagged cache item, pass the same ordered list of tags to the `tags

You may flush all items that are assigned a tag or list of tags. For example, this statement would remove all caches tagged with either `people`, `authors`, or both. So, both `Anne` and `John` would be removed from the cache:

태그 또는 태그 목록이 지정된 아이템들을 모두 지울 수 있습니다. 예를 들어 다음 코드는 `people` 또는 `authors` 또는 둘 모두에 태그가 지정된 모든 캐시 된 항목들이 삭제됩니다. 그러므로 "Anne"과 "John"두 아이템은 캐시에서 제거됩니다:
태그 또는 태그 목록이 지정된 아이템을 모두 지울 수 있습니다. 예를 들어 다음 코드는 `people` 이나 `authors`, 또는 둘 모두에 태그가 지정된 모든 캐시된 항목이 삭제됩니다. 그러므로 "Anne"과 "John" 두 아이템은 캐시에서 제거됩니다:

In contrast, this statement would remove only caches tagged with `authors`, so `Anne` would be removed, but not `John`:

한편, 다음 코드에서는 `authors` 태그 된 캐시 만 삭제되기 때문에 `Anne`은 삭제되지만 `John`는 남아 있습니다:
한편, 다음 코드에서는 `authors` 태그된 캐시만 삭제되기 때문에 `Anne`은 삭제되지만 `John`는 남아 있습니다:

@@ -360,7 +360,7 @@ To create our custom cache driver, we first need to implement the `Illuminate\Co

We just need to implement each of these methods using a MongoDB connection. For an example of how to implement each of these methods, take a look at the `Illuminate\Cache\MemcachedStore` in the framework source code. Once our implementation is complete, we can finish our custom driver registration.

이제 각각의 메소드를 MongoDB 연결을 사용하여 구현해야합니다. 각각의 이 메소드들이 어떻게 구현되는지 예를 들어보자면, 프레임워크 소스 코드 상에서 `Illuminate\Cache\MemcachedStore` 를 살펴보도록 하겠습니다. 구현을 완료하면, 이제 사용자 정의 드라이버를 등록하면 됩니다.
이제 MongoDB 연결을 사용하여 각각의 메소드를 구현해야 합니다. 각각의 메소드가 어떻게 구현되는가에 대한 예시로, 프레임워크 소스 코드 상에서 `Illuminate\Cache\MemcachedStore` 를 살펴보도록 하겠습니다. 구현을 완료하면 사용자 정의 드라이버를 등록할 수 있습니다.

@@ -368,7 +368,7 @@ We just need to implement each of these methods using a MongoDB connection. For 

> {tip} If you're wondering where to put your custom cache driver code, you could create an `Extensions` namespace within your `app` directory. However, keep in mind that Laravel does not have a rigid application structure and you are free to organize your application according to your preferences.
> 
> {tip} 만약 여러분이 구성한 캐시 드라이버 코드를 어디헤 놓아둘지 고민된다면, `app` 디렉토리안에 `Extensions` 네임스페이스를 만들 수도 있습니다. 하지만, 기억할 것은 라라벨은 엄격한 어플리케이션 구조를 가지고 있지 않기 때문에, 어느곳이든 여러분이 설정하고자 하는 곳에 코드를 둘 수 있다는 점입니다.
> {tip} 만약 여러분이 구성한 캐시 드라이버 코드를 어디에 놓아둘지 고민된다면, `app` 디렉토리 안에 `Extensions` 네임스페이스를 만들 수도 있습니다. 하지만, 라라벨은 엄격한 어플리케이션 구조를 가지고 있지 않기 때문에, 어느 곳이든 여러분이 설정하고자 하는 곳에 코드를 둘 수 있다는 점을 기억하세요.

@@ -376,7 +376,7 @@ We just need to implement each of these methods using a MongoDB connection. For 

To register the custom cache driver with Laravel, we will use the `extend` method on the `Cache` facade. The call to `Cache::extend` could be done in the `boot` method of the default `App\Providers\AppServiceProvider` that ships with fresh Laravel applications, or you may create your own service provider to house the extension - just don't forget to register the provider in the `config/app.php` provider array:

사용자 정의 캐시 드라이버를 라라벨에 등록하기 위해서, `Cache` 파사드의 `extend` 메소드를 사용할 것입니다. `Cache::extend` 호출은 라라벨 어플리케이션 설치시 제공되는 `App\Providers\AppServiceProvider`의 `boot` 메소드에서 수행되거나, 고유한 서비스 프로바이더를 생성할 수 있습니다. - 프로바이더를 `config/app.php` 파일 안에 있는 프로바이더 배열에 등록하는 것을 잊지 마십시오: 
사용자 정의 캐시 드라이버를 라라벨에 등록하기 위해서, `Cache` 파사드의 `extend` 메소드를 사용할 것입니다. `Cache::extend` 호출은 라라벨 어플리케이션 설치시 제공되는 `App\Providers\AppServiceProvider`의 `boot` 메소드를 사용하거나, extension 을 제공하는 고유한 서비스 프로바이더를 생성해서 쓸 수 있습니다. - 프로바이더를 `config/app.php` 파일 안에 있는 프로바이더 배열에 등록하는 것을 잊지 마십시오:

@@ -413,11 +413,11 @@ To register the custom cache driver with Laravel, we will use the `extend` metho

The first argument passed to the `extend` method is the name of the driver. This will correspond to your `driver` option in the `config/cache.php` configuration file. The second argument is a Closure that should return an `Illuminate\Cache\Repository` instance. The Closure will be passed an `$app` instance, which is an instance of the [service container](/docs/{{version}}/container).

`extend` 메소드에 전달되는 첫번째 인자는 드라이버의 이름입니다. 이 이름은 `config/cache.php` 설정 파일의 `driver` 옵션에 해당합니다. 두번째 인자는 `Illuminate\Cache\Repository` 인스턴스를 반환하는 클로저가 됩니다. 클로저에는 `$app` 인스턴스가 전달되는데, 이 인자는 [서비스 컨테이너](/docs/{{version}}/container)의 인스턴스입니다. 
`extend` 메소드에 전달되는 첫 번째 인자는 드라이버의 이름입니다. 이 이름은 `config/cache.php` 설정 파일의 `driver` 옵션에 해당합니다. 두 번째 인자는 `Illuminate\Cache\Repository` 인스턴스를 반환하는 클로저가 됩니다. 클로저에는 `$app` 인스턴스가 전달되는데, 이 인자는 [서비스 컨테이너](/docs/{{version}}/container)의 인스턴스입니다.

Once your extension is registered, simply update your `config/cache.php` configuration file's `driver` option to the name of your extension.

드라이버 확장이 등록되고 나면, `config/cache.php` 설정 파일의 `driver` 옵션을 추가한 이름으로 변경하면 됩니다. 
extension 이 등록되고 나면, `config/cache.php` 설정 파일의 `driver` 옵션을 추가한 extension의 이름으로 변경하면 됩니다.

@@ -425,7 +425,7 @@ Once your extension is registered, simply update your `config/cache.php` configu

To execute code on every cache operation, you may listen for the [events](/docs/{{version}}/events) fired by the cache.

캐시가 동작할 때에 특정한 코드를 실행하기 위해서는 캐시에 의해서 실행되는 이벤트 리스너를 등록해야 합니다.
캐시가 동작할 때에 특정한 코드를 실행하기 위해서는 캐시에 의해 실행되는 이벤트 리스너를 등록해야 합니다.

---

extension이라는 단어가 어떻게 해석되는지 모르겠네요.

**Comment by findstar** [comment]
검수 반영후 수정하였습니다. extension 은 그냥 써도 될것 같아요.
