### ISSUE TITLE
매뉴얼 상단 '영어 원문보기' 링크 오류

### ISSUE THREAD

**Issue by natz92** [laravelkr/docs#115]
영어 원문보기 링크에 docs 와 버전 태그 사이 '/' 가 누락되어 있습니다.

-  앵커된 링크 : https://laravel.com/docs5.7/encryption
-  올바른 링크 : https://laravel.com/docs/5.7/encryption

**Comment by kkame** [comment]
감사합니다
수정 완료하였습니다
