### ISSUE TITLE
configuration 1차 검수

### ISSUE THREAD

**Issue by paikwiki** [laravelkr/docs#13]
@@ -28,13 +28,13 @@ All of the configuration files for the Laravel framework are stored in the `conf

A default value may also be specified and will be returned if the configuration option does not exist:

설정된 옵션 값이 존재하지 않았을 때 반환될 기본 값을 지정할 수도 있습니다.
설정된 옵션값이 존재하지 않았을 때 반환될 **기본값을** 지정할 수 있습니다.

```
$value = config('app.timezone');
```

To set configuration values at runtime, pass an array to the `config` helper:

어플리케이션의 실행중에 설정 값을 변경하려면 `config` 헬퍼에 배열을 전달 하십시오:
어플리케이션의 실행중에 **설정값을** 변경하려면 `config` 헬퍼에 배열을 **전달하십시오**:

@@ -44,32 +44,32 @@ To set configuration values at runtime, pass an array to the `config` helper:

It is often helpful to have different configuration values based on the environment the application is running in.

프로그램이 실행되는&nbsp;&nbsp;구동환경에 따라 다른 설정값을 사용할 수 있으면 많은 이점이 있습니다.
프로그램이 **실행되는 구동환경에** 따라 다른 설정값을 사용할 수 있으면 많은 이점이 있습니다.

To make this a cinch, Laravel utilizes the [DotEnv](https://github.com/vlucas/phpdotenv) PHP library by Vance Lucas. In a fresh Laravel installation, the root directory of your application will contain a `.env.example` file. If you install Laravel via Composer, this file will automatically be renamed to `.env`. Otherwise, you should rename the file manually.

보다 확실하게 하기 위해서 라라벨은 Vance Lucas가 만든 PHP 라이브러리 [DotEnv](https://github.com/vlucas/phpdotenv)을 이용합니다. 새롭게 라라벨을 인스톨 한경우에 어플리케이션의 루트 디렉토리에 `.env.example` 파일이 포함되어 있습니다. 컴포저를 통해서 설치한 경우에는 이 파일이 자동으로 `.env`파일로 변경됩니다. 컴포저를 사용하지 않는다면 직접 파일을 변경하십시오.

> "위의 단락이 #### Retrieving Environment Configuration 위에 위치해야 하는데
> #### Retrieving Environment Configuration 아래에 위치하고 있습니다.
> 
> 수정할 내용은 없습니다.-chpaik"

All of the variables listed in this file will be loaded into the `$_ENV` PHP super-global when your application receives a request. However, you may use the `env` helper to retrieve values from these variables in your configuration files.

이 파일의 목록에 있는 모든 변수들은 어플리케이션이 요청을 받으면 `$_ENV` PHP 슈퍼 전역변수에 로드됩니다. `env` 헬퍼 함수를 통해서 설정 파일안에 있는 이러한 변수값들을 조회 할 수 있습니다.
이 파일의 목록에 있는 모든 **변수는 어플리케이션이 요청을 받을 때** `$_ENV` PHP 슈퍼 전역변수에 로드됩니다. `env` 헬퍼 함수를 통해서 설정 파일 안에 있는 이러한 변수값들을 **조회할** 수 있습니다.

The second value passed to the `env` function is the "default value". This value will be used if no environment variable exists for the given key.

`env` 함수에 전달되는 두번째 인자는 "기본값" 입니다. 이 값은 주어진 환경 이름이 존재하지 않을 경우에 사용될것입니다.
`env` 함수에 전달되는 **두 번째** 인자는 "기본값" 입니다. 이 값은 주어진 **키를 위한 환경 변수가 존재하지 않을 때 사용될 것**입니다.

By putting place-holder values in the example configuration file, other developers on your team can clearly see which environment variables are needed to run your application.

example 설정 파일에 적절한 기본값을 넣어두면 다른 개발자들이 응용 프로그램을 실행하는 데 어떤 환경 변수 설정이 필요한지 명확하게 이해할 수 있습니다.
example 설정 파일에 적절한 기본값을 넣어두면 다른 개발자들이 **어플리케이션**을 실행하는 데 어떤 환경 변수 설정이 필요한지 명확하게 이해할 수 있습니다.

@@ -77,13 +77,13 @@ If you are developing with a team, you may wish to continue including a `.env.ex

You may access this value via the `environment` method on the `App` [facade](/docs/{{version}}/facades):

`App` [파사드](/docs/{{version}}/facades)의 `environment` 메소드를 통해서 이 값에 접근 할 수 있습니다:
`App` [파사드](/docs/{{version}}/facades)의 `environment` 메소드를 통해서 이 값에 **접근할** 수 있습니다:

You may also pass arguments to the `environment` method to check if the environment matches a given value. The method will return `true` if the environment matches any of the given values:

또한 `environment` 메소드에 확인하고자 하는 구동 환경에 대한 값을 인자로 전달 할 수도 있습니다. 메소드는 주어진 값들에 일치하는게 하나라도 있다면 `true`를 반환할 것입니다.
또한 `environment` 메소드에 확인하고자 하는 구동 환경에 대한 값을 인자로 **전달할 수** 있습니다. 메소드는 주어진 값들에 **일치하는 게** 하나라도 있다면 `true`를 반환할 것입니다.

@@ -99,11 +99,11 @@ You may also pass arguments to the `environment` method to check if the environm

This will combine all of the configuration options for your application into a single file which will be loaded quickly by the framework.

이 명령어는 모든 설정 옵션들을 하나의 파일로 묶어 어플리케이션이 빠르게 로드할 수 있게 해줍니다.
이 명령어는 모든 설정 **옵션을** 하나의 파일로 묶어 어플리케이션이 빠르게 로드할 수 있게 해줍니다.

The command should not be run during local development as configuration options will frequently need to be changed during the course of your application's development.

어플리케이션 개발 중에는 설정 옵션 값이 자주 바뀔 필요가 있기 때문에, 로컬 개발 환경에서는 이 명령어를 실행하지 말아야 합니다.
어플리케이션 개발 중에는 설정 **옵션값이** 자주 바뀔 필요가 있기 때문에, 로컬 개발 환경에서는 이 명령어를 실행하지 말아야 합니다.

**Comment by findstar** [comment]
검수 이슈 반영하여 수정하였습니다.
