### ISSUE TITLE
contributions.md 1차 검수

### ISSUE THREAD

**Issue by paikwiki** [laravelkr/docs#14]
@@ -20,17 +20,17 @@
However, if you file a bug report, your issue should contain a title and a clear description of the issue. You should also include as much relevant information as possible and a code sample that demonstrates the issue. The goal of a bug report is to make it easy for yourself - and others - to replicate the bug and develop a fix.
However, if you file a bug report, your issue should contain a title and a clear description of the issue. You should also include as much relevant information as possible and a code sample that demonstrates the issue. The goal of a bug report is to make it easy for yourself - and others - to replicate the bug and develop a fix.

버그 리포트를 작성하는 경우, 이슈는 제목과 이슈에 대한 명확한 설명을 포함해야합니다. 또한 해당 이슈에 대한 가능한 많은 관련 정보와 데모 코드 샘플을 포함해야 합니다. 버그 리포트의 목적은 여러분 자신과 그리고 다른 사람들도 쉽게 버그를 재현 할 수 있도록 하고 버그가 수정되도록 하는 것 입니다.
버그 리포트를 작성하는 경우, 이슈는 제목과 이슈에 대한 명확한 설명을 **포함해야 합니다**. 또한 해당 이슈에 대한 가능한 많은 관련 정보와 데모 코드 샘플을 포함해야 합니다. 버그 리포트의 목적은 **여러분 자신과 다른 사람들이 쉽게 버그를 재현하고, 수정할 수 있게 하는 것입니다.**

Remember, bug reports are created in the hope that others with the same problem will be able to collaborate with you on solving it. Do not expect that the bug report will automatically see any activity or that others will jump to fix it. Creating a bug report serves to help yourself and others start on the path of fixing the problem.
Remember, bug reports are created in the hope that others with the same problem will be able to collaborate with you on solving it. Do not expect that the bug report will automatically see any activity or that others will jump to fix it. Creating a bug report serves to help yourself and others start on the path of fixing the problem.

명심할 것은 버그 리포트가 같은 문제에 있던 다른 사람들과 문제를 해결하기 위해 협력 할 수 있는 기회을 만든다는 것입니다. 버그 리포트를 통해 자동으로 뭔가가 일어나고, 다른 누군가가 문제를 해결하기를 기대하지 마십시오. 버그 리포트 제출은 여러분 자신과 다른 사람이 문제를 해결하는 길을 시작하는 계기가 되는 것입니다.
버그 리포트를 통해 같은 문제를 겪고 있는 다른 사람들과 협력해서 그 문제를 해결할 수 있다는 것을 명심하세요. 버그 리포트가 자동으로 어떤 활동을 만들어 내거나, 다른 이들이 버그을 고칠 것이라는 기대를 하지 마십시오. 버그 리포트 제출은 여러분 자신과 다른 사람이 문제를 해결할 수 있는 길에 들어설 수 있도록 하는 것입니다.

@@ -61,11 +61,11 @@ The Laravel source code is managed on Github, and there are repositories for eac

If you propose a new feature, please be willing to implement at least some of the code that would be needed to complete the feature.

새로운 기능을 제안하는 경우 자발적으로 기능을 구동 시키는 데 필요한 코드를 최소한으로 구현하시기 바랍니다.
새로운 기능을 제안하는 경우 자발적으로 기능을 **구동시키는** 데 필요한 코드를 최소한으로 구현하시기 바랍니다.

Informal discussion regarding bugs, new features, and implementation of existing features takes place in the `#internals` channel of the [LaraChat](http://larachat.co) Slack team.

일상적으로, 버그와 관련 및 새로운 기능과 기존 기능의 구현에 대한 논의는 [LaraChat](http://larachat.co)의 `#internals` 채널에서 진행됩니다.
버그와 관련 및 새로운 기능과 기존 기능의 구현에 대한 **격식에 얽매이지 않은 일상적인** 논의는 [LaraChat](http://larachat.co)의 `#internals` 채널에서 진행됩니다.

@@ -109,7 +109,7 @@ Laravel follows the [PSR-2](https://github.com/php-fig/fig-standards/blob/master

Below is an example of a valid Laravel documentation block. Note that the `@param` attribute is followed by two spaces, the argument type, two more spaces, and finally the variable name:

다음은 유효한 라라벨 문서 블록의 예시입니다. `@param` 속성은 2개의 스페이스가 뒤에 오고, 인수의 타입, 2개 이상의 스페이스로 구성되어, 마지막에 변수의 이름이 위치하게 됩니다:
다음은 유효한 라라벨 문서 블록의 예시입니다. **`@param` 속성 뒤에는 2개의 스페이스, 인수의 타입, 다시 2개의 스페이스, 마지막으로 변수의 이름이 위치합니다:**

@@ -130,4 +130,4 @@ Below is an example of a valid Laravel documentation block. Note that the `@para

[StyleCI](https://styleci.io/) will automatically merge any style fixes into the Laravel repository after pull requests are merged.

PR 이 Merge 될 때 [StyleCI](https://styleci.io/)가 자동으로 스타일을 수정하고 라라벨 저장소에 머지할 것입니다.
**PR이** Merge 될 때 [StyleCI](https://styleci.io/)가 자동으로 스타일을 수정하고 라라벨 저장소에 머지할 것입니다.

**Comment by findstar** [comment]
검수 이슈 반영되어 수정되었습니다
