### ISSUE TITLE
[6.0] 번역 기여자 모집

### ISSUE THREAD

**Issue by kkame** [laravelkr/docs#168]
# 6.0 번역 기여자 모집

- 모집마감 : 8월 31일
- 번역마감 : 9월 14일

- 지원방법 : 하단에 아래의 양식으로 댓글을 남겨주세요

```
라라벨 개발 경험 :  O or X
문서 번역 경험: O or X
맡고 싶은 챕터(파일기준): ~~~.md
```

## 번역 방식
- 5.8의 번역 문서를 기준으로 6.0의 변경된 내역을 업데이트
- 전체 문서 재번역을 권장하지 않음
  - 기존 문서와의 호환성 염두
- 준비가 완료되면 pre-kr-6.0 브랜치에서 작업
- 모집이 종료되면 작업 분량에 대해 각자의 레포에서 작업하신 이후에 pr을 통해서 번역본을 전달
- 관리자의 최종 문장 감수 이후에 kr-6.0 브랜치에 머지

### 5.8과의 작업 변경점
- 변경 이력이 없는 파일도 검수 대상으로 분류
- 6.x버전 신규 출시와 함께 문서 전체의 재검수를 통해 퀄리티 상승을 유도
- 한글로 번역 후 매끄럽지 못한 문장을 교정
  - 기존의 번역문서도 교정이 필요한 경우라면 관련 버전들도 pr추천
- 단어 선정이나 표현의 방식을 수정해야 할 필요가 있을 경우 별도 이슈 생성
  - 관련하여 작업하는 분들과 모두 공유 및 논의

## 오픈일정
- 번역 마감 후 편집 하여 9월 중 공개

## 기여에 대한 보상
- 사이트 첫화면 및 깃헙 기여자 표시 추가
- 수정한 문서의 하단 기여자의 깃허브 계정 표시 추가

## 번역 리스트

- [x] api-authentication.md @lucyholic
- [x] artisan.md
- [x] authentication.md @lucyholic
- [x] authorization.md @lucyholic
- [x] billing.md @fwang-laralabs
- [x] blade.md @adrinerDP
- [x] broadcasting.md
- [x] cache.md
- [x] collections.md @ukits
- [x] configuration.md
- [x] console-tests.md
- [x] container.md @meteopark
- [x] contracts.md
- [x] contributions.md
- [x] controllers.md
- [ ] csrf.md @devSeok
- [x] database-testing.md
- [x] database.md
- [x] deployment.md
- [x] documentation.md
- [x] dusk.md @fwang-laralabs
- [x] eloquent-collections.md @lucyholic
- [x] eloquent-mutators.md
- [x] eloquent-relationships.md @lucyholic
- [x] eloquent-resources.md
- [x] eloquent-serialization.md
- [x] eloquent.md @getsolaris
- [x] encryption.md
- [x] envoy.md @fwang-laralabs
- [x] errors.md @cherryred5959
- [x] events.md @cherryred5959 
- [x] facades.md
- [x] filesystem.md @lucyholic
- [x] frontend.md
- [x] hashing.md
- [x] helpers.md @picory
- [x] homestead.md
- [x] horizon.md @AcidF0x
- [x] http-tests.md
- [x] installation.md
- [x] license.md
- [x] lifecycle.md
- [x] localization.md @adrinerDP
- [x] logging.md
- [x] mail.md @jungmyungzZ
- [x] middleware.md @jdssem
- [x] migrations.md @KangPilGyu
- [x] mix.md
- [x] mocking.md @picory
- [x] notifications.md
- [x] packages.md
- [x] pagination.md @KangPilGyu
- [x] passport.md
- [x] passwords.md
- [x] providers.md
- [x] queries.md
- [x] queues.md @dhtmdgkr123
- [x] readme.md
- [x] redirects.md
- [x] redis.md @KangPilGyu
- [x] releases.md @yupmin
- [x] requests.md @horace-velmont
- [x] responses.md @horace-velmont
- [x] routing.md @jungmyungzZ
- [x] scheduling.md
- [x] scout.md
- [x] seeding.md
- [x] session.md
- [x] socialite.md @AcidF0x
- [x] structure.md
- [x] telescope.md
- [x] testing.md @picory
- [x] upgrade.md @whdckszxxx
- [x] urls.md @AcidF0x
- [x] valet.md
- [x] validation.md @lucyholic
- [x] verification.md @jdssem
- [x] views.md

**Comment by kkame** [comment]
번역이 처음이라 이전에 어떤식으로 진행하였는지 궁금하신 분은
[5.8번역 이슈](https://github.com/laravelkr/docs/issues/105) 에서 내용을 확인 하실 수 있습니다.

**Comment by gaejabong** [comment]
라라벨 경험 :  O
번역 경험: O
맡고 싶은 챕터(파일기준): middleware.md

**Comment by getsolaris** [comment]
라라벨 경험 : O
번역 경험: O
맡고 싶은 챕터(파일기준): eloquent.md

**Comment by lucyholic** [comment]
라라벨 경험: O
번역 경험: O
맡고싶은 챕터: filesystem.md, validation.md

**Comment by fwang-laralabs** [comment]
라라벨 경험 :  O
번역 경험: X
맡고 싶은 챕터 :  envoy.md , billing.md , dusk.md

**Comment by adrinerDP** [comment]
라라벨 경험 : O
번역 경험: X
맡고 싶은 챕터(파일기준): blade.md, localization.md

**Comment by meteorpark** [comment]
라라벨 경험 : O
번역 경험 : X
맡고 싶은 챕터(파일기준) : container.md

**Comment by horace-velmont** [comment]
라라벨경험 : O
번역 경험: X (라라벨 외 프로젝트 번역 경험 O)
맡고 싶은챕터(파일기준): requests.md, responses.md

**Comment by yupmin** [comment]
라라벨경험 : O
번역 경험: O
맡고 싶은챕터(파일기준): releases.md

**Comment by ukits** [comment]
라라벨경험 : O
번역 경험: O
맡고 싶은챕터(파일기준): collections.md

**Comment by KangPilGyu** [comment]
라라벨경험 : O
번역 경험: X
맡고 싶은챕터(파일기준): pagination.md, migration.md, redis.md

**Comment by picory** [comment]
라라벨 경험: O
번역 경험: X
맡고 싶은챕터(파일기준): helpers.md, mocking.md, testing.md

**Comment by chanzxxx** [comment]
라라벨 경험 :  O
번역 경험: O
맡고 싶은 챕터(파일기준): upgrade.md

**Comment by youaresodalgona** [comment]
라라벨 경험 : O
번역 경험: O
맡고 싶은 챕터(파일기준): errors.md, events.md

**Comment by devSeok** [comment]
라라벨 경험 : O
번역 경험 : X
맡고 싶은 챕터(파일기준) : csrf.md

**Comment by 0xFoxTail** [comment]
라라벨 경험 : O
번역 경험 : O
맡고 싶은 챕터(파일기준) : horizon.md,  socialite.md,  urls.md

**Comment by JeongmyeongzZ** [comment]
라라벨 경험 : O
번역 경험 : X
맡고 싶은 챕터(파일기준) : mail.md

**Comment by kkame** [comment]
## 추가안내

### 처음 번역을 해보시는 (해보고 싶은) 분을 위한 안내
우리는 전문 번역가가 아닙니다
- 그럼에도 불구하고 모두가 라라벨의 더 나은 생태계를 위해 같이 노력해서 지금의 문서가 만들어졌다고 생각합니다.
- 번역에 오타가 있고 오역이 있더라도 해당 문서를 보시는 분들과 함께 고쳐나가면 됩니다
- 참여해보고 싶었지만 용기가 없었던 분들은 아직 늦지 않았으니 지원해주세요.

### 추가 번역 참여 안내
- 늦게라도 참여하시고 싶으신 분은 상단의 문서리스트에서 담당자가 지정되지 않고 체크처리되지 않은 문서는 여전히 참여가 가능합니다.
- 번역이 일찍 끝나신 분들 중에서 추가적으로 문서 번역이 가능하신 분들은 추가 신청해주셔도 됩니다.

### 번역분량 조율 안내
- 번역은 생각보다 시간이 많이 들어가는 일입니다. 오랜시간을 투자해야하는 만큼 일정의 변동이 생기기 쉽습니다.
- 따라서 번역도중 일정이 생겨 분량의 조절이 필요하신 분은 주저없이 말씀해주세요. 최대한 조율해드리겠습니다.

### 감수자 일정 안내
- 감수자의 경우 이번 번역건이 다 취합된 이후에 별도 모집을 하도록 하겠습니다. 
  - 즉 이번에는 본인의 담당 파일의 번역에만 집중해주시면 됩니다.

**Comment by kkame** [comment]
### pre-kr-6.0 브랜치 추가 완료하였습니다.
번역하시면서 궁금하신 사항은
[모던퍼그의 슬랙](https://modernpug.org/slack) #laravel-doc-translator 채널에서 문의해주시면 됩니다

### 표준 작업 절차
-  pre-kr-6.0 브랜치를 자신의 깃허브 계정으로 fork
- kr 폴더내의 자신이 담당하는 파일에 존재하는 5.8의 내용을 원문과 번역문 모두 6.0으로 업데이트
- 완료된 문서를 pull request로 제출

#### 주의사항
- 브랜치 최상단에 존재하는 파일은 원문을 트래킹하기 위한 파일이니 kr 폴더외의 파일은 수정하지 않습니다.
- kr 폴더내의 파일은 원문과 번역문을 모두 보며 비교하기 위한 파일이니 기존의 작성 스타일을 유지해주세요
- 한글만 존재하는 파일은 kr-6.0브랜치 내에서 관리자가 별도로 관리하니 따로 작업하지 않으셔도 됩니다.

**Comment by dhtmdgkr123** [comment]
라라벨 경험 : O
번역 경험 : x
맡고 싶은 챕터(파일기준) : queues.md

**Comment by gaejabong** [comment]
`middleware.md`는 변동사항이 없습니다.
`verification.md`를 추가로 번역해 보겠습니다!!

**Comment by 0xFoxTail** [comment]
socialite.md, urls.md 변동사항 없음

**Comment by lucyholic** [comment]
제가 맡은 부분도 변동사항이 없어 filesystem.md, validation.md로 변경하겠습니다

**Comment by lucyholic** [comment]
위의 두 파일이 일찍 끝나서 api-authentication.md, authentication.md, authorization.md 도 추가로 하겠습니다.

**Comment by horace-velmont** [comment]
reponses.md, requests.md 작업 및 머지완료 되었습니다!

**Comment by JeongmyeongzZ** [comment]
routing 추가로 작업하겠습니다!

**Comment by kkame** [comment]
## 추가 번역을 하시는 분들을 위한 안내입니다
- 이슈 본문에 존재하는 문서의 리스트에 체크가 된 문서는 번역이 완료된 문서들입니다
- 담당자가 지정되어있지 않고 체크박스에 체크가 되어있지 않은 문서를 위주로 번역을 신청해주세요
  - 체크가 안된 문서는 제가 상단에서부터 순서대로 번역하고 있는 중입니다

### 번역문장 교정시 참고 안내

확실히 사람들이 많아지니깐 전체적으로 번역의 퀄리티가 올라가고 있는 것 같아서 기분이 좋습니다.
참여해주시는 분들 모두 정말 감사합니다.

저도 시간과 마음의 여유가 조금 생기니 표현에서 조금 더 수정하면 좋을 게 눈에 보이는데요

- 수동태를 능동태 문장으로 고쳤으면 좋겠습니다
  - ex) `~~~가 되다` -> `~~~를 하다` 
- 번역 후 한글 표현에 있는 마침법 표기 `:`가 영문에 있던 그대로 사용된 부분을 `.`로 고쳤으면 좋겠습니다
  - ex) `~~~~ 합니다:` -> `~~~~ 합니다.`
  - 영어부분은 손대지 않습니다. 한글에서 `:` 라는 마침표는 안쓰기 떄문에 한글만 변경합니다

다들 추가적으로 의견 주실만한게 있으시다면 의견을 주시면 좋을 것 같습니다

**Comment by youaresodalgona** [comment]
`events.md` 파일은 변동사항이 없습니다~

**Comment by adrinerDP** [comment]
`localization.md` 변동사항 없습니다!

**Comment by fwang-laralabs** [comment]
envoy.md , billing.md : 변경사항 없습니다.
dusk.md  : pull request 완료.

**Comment by picory** [comment]
helpers.md : PR 완료
mocking.md : PR 완료
testing.md : PR 완료

**Comment by gaejabong** [comment]
`middleware.md`, `verification.md` 번역 완료하여 PR 하였습니다.

**Comment by picory** [comment]
`helpers.md` `mocking.md` `testing.md` 번역 완료, PR

**Comment by kkame** [comment]
번역이 대부분 마무리되었고 이제는 문서 출시를 위해 이슈를 닫도록 하겠습니다. 
참여해주신 모든 분들 수고하셨습니다~
