### ISSUE TITLE
[6.0] 번역 감수자 모집

### ISSUE THREAD

**Issue by kkame** [laravelkr/docs#186]
### 기간 안내
- 감수 시작 : 9월14일 이후 또는 현재 진행중인 6.0 번역이 완료된 시점에 시작합니다
- 감수 종료 : 9월 28일

감수는 하다가 보면 끝이 나지 않을 가능성이 높기 때문에 28일까지 접수 된 사항을 기준으로 마감하며
그 외에는 10월1일(예상) 한글 문서가 출시 된 이후에 PR 또는 이슈를 통해서 자유롭게 추가 의견을 주시면 됩니다

### 감수자 지원안내
- 특정 파일을 집중적으로 감수 하실 분
  - 댓글로 본인이 희망하는 파일에 대해 지원하시면 됩니다
- 좀 더 자유롭게 감수하실 분
  - 특정 파일을 언급하지 않고 자유롭게 파일을 보시다가 교정할 점이 발견되면 PR하시면 됩니다
- 감수가 끝난 파일의 내용을 같이 검토 하실 분
  - 별도의 지원은 하지 않으셔도 되며 PR이 등록될 경우 리뷰 코멘트를 같이 달아주시면 됩니다

### 작업방식
- pre-kr-6.0 브랜치를 자신의 레포지러티로 포크 합니다
- 최상단에 존재하는 파일과 kr 폴더에 존재하는 파일의 영문이 동일한지 확인합니다
  - 가끔 변경사항이 누락되는 파일들이 있습니다
- 한글 부분을 읽고 더 자연스럽게 이해 될 수 있는 문장으로 교정합니다
  - 애매하다고 느끼는 부분은 수정 후 PR을 통해 다른 분들과 같이 의견을 교환합니다
  - 한글 번역문에서 마침표가 `:`로 된 것을 `.`로 교정합니다
  - 수동태 문장을 능동태로 교정합니다
    - ex) `~~~가 되다` -> `~~~를 하다`
- PR로 변경내역을 전송합니다
  - 관리자 및 다른 리뷰어가 리뷰를 한 후 최종 머지합니다

## 감수 리스트
- [ ] api-authentication.md
- [ ] artisan.md
- [ ] authentication.md
- [ ] authorization.md
- [ ] billing.md
- [ ] blade.md
- [ ] broadcasting.md
- [ ] cache.md
- [ ] collections.md
- [ ] configuration.md
- [ ] console-tests.md
- [ ] container.md
- [ ] contracts.md
- [ ] contributions.md
- [ ] controllers.md
- [ ] csrf.md
- [ ] database-testing.md
- [ ] database.md
- [ ] deployment.md
- [ ] documentation.md
- [ ] dusk.md
- [ ] eloquent-collections.md
- [ ] eloquent-mutators.md
- [ ] eloquent-relationships.md
- [ ] eloquent-resources.md
- [ ] eloquent-serialization.md
- [ ] eloquent.md
- [ ] encryption.md
- [ ] envoy.md
- [ ] errors.md
- [ ] events.md 
- [ ] facades.md
- [ ] filesystem.md
- [ ] frontend.md
- [ ] hashing.md
- [ ] helpers.md
- [ ] homestead.md
- [ ] horizon.md
- [ ] http-tests.md
- [ ] installation.md
- [ ] license.md
- [ ] lifecycle.md
- [ ] localization.md
- [ ] logging.md
- [ ] mail.md
- [ ] middleware.md
- [ ] migrations.md
- [ ] mix.md
- [ ] mocking.md
- [ ] notifications.md
- [ ] packages.md
- [ ] pagination.md
- [ ] passport.md
- [ ] passwords.md
- [ ] providers.md
- [ ] queries.md
- [ ] queues.md
- [ ] readme.md
- [ ] redirects.md
- [ ] redis.md
- [ ] releases.md
- [ ] requests.md
- [ ] responses.md
- [ ] routing.md
- [ ] scheduling.md
- [ ] scout.md
- [ ] seeding.md
- [ ] session.md
- [ ] socialite.md
- [ ] structure.md
- [ ] telescope.md
- [ ] testing.md
- [ ] upgrade.md
- [ ] urls.md
- [ ] valet.md
- [ ] validation.md
- [ ] verification.md
- [ ] views.md

**Comment by 14km** [comment]
cache.md
 collections.md
 configuration.md
 console-tests.md

일단 이 4개를.. 해보고싶습니당

수가로 빨리 끝난다고 하면 

container.md
 contracts.md
 contributions.md
 controllers.md
 csrf.md

정도 ..?

**Comment by kkame** [comment]
이제는 문서의 출시일이 다가옴에 따라 이 이슈는 닫도록 하겠습니다

감수와 수정은 이 이슈와 관계없이 상시로 받고 있으니 나중에라도 개선하고 싶은 사항들이 발견되면 PR주세요

참여해주셔서 감사합니다
