### ISSUE TITLE
컨텐츠간에 이동 모션이 불편합니다.

### ISSUE THREAD

**Issue by santutu** [laravelkr/docs#212]
Contents 에서 메뉴를 통해 이동할 때 이동 모션이 너무 오래 걸립니다. (이동하는 거리가 클 수록 오래걸립니다.)

**Comment by 0xFoxTail** [comment]
@santutu 
[laravelkr/website](https://github.com/laravelkr/website) 이쪽으로 이슈를 작성하는게 좋을거같습니다.

말씀하신대로 느린거 같긴 합니다.
