### ISSUE TITLE
6.x 오타를 찾았습니다.

### ISSUE THREAD

**Issue by initred** [laravelkr/docs#228]
### 요청사항
https://laravel.kr/docs/6.x/queries

groupBy 와 hanving 메소드는 쿼리 결과를 그룹화하는데 사용합니다. having 메소드는 where 메소드와 사용장법이 비슷합니다.

having인데 hanving으로 오타가 났습니다.

**Comment by kkame** [comment]
안녕하세요~

늦었지만 알려주신 내용 수정완료하였습니다

감사합니다!

**Comment by kkame** [comment]
@all-contributors please add @initred for doc
