### ISSUE TITLE
기여자 수정 요청

### ISSUE THREAD

**Issue by njhyuk** [laravelkr/docs#278]
### 대상 버전
master

### 요청사항
@kkame 
[testing.md 번역](https://github.com/laravelkr/docs/pull/270) 작업을 했었습니다.
레포는 개인계정(njhyuk) 으로 [레포를 포크](https://github.com/njhyuk/docs/tree/pre-kr-7.x) 받았는데요.
커밋은 회사계정(junhyuk-noh-kurly) 으로 해서 기여자가 회사 계정으로 올라 간 것 으로 추측 됩니다.
개인계정(njhyuk) 으로 수정 가능 하실까요? ㅠ_ㅠ

**Comment by kkame** [comment]
금일문서 편집 이후에 아직 기여자로 등록되지 못한 분들 정리를 하려고 하는데 그때 같이 정리해드리겠습니다~

**Comment by kkame** [comment]
수정완료하였습니다
