### ISSUE TITLE
[7.x]오타.md

### ISSUE THREAD

**Issue by DungGi** [laravelkr/docs#316]
### 대상 버전
7.x

### 요청사항
Eloquent: 시작하기
-> 테이블 이름 부분에 
생성한 Flight 모델에서 어떠한 테이블을 사용해야할지 **Elquent** 에게 알려주지 않았다는
이부분에 Elquent가 오타가 난 것 같습니다.

### 참고사항

**Comment by kkame** [comment]
감사합니다 수정완료하였습니다

**Comment by kkame** [comment]
@all-contributors please add @DungGi  for doc
