### ISSUE TITLE
[8.x] 문서 업데이트 

### ISSUE THREAD

**Issue by kkame** [laravelkr/docs#359]
### 참여방법
- 댓글로 참여를 원하시는 문서를 남겨 주시면 해당 문서의 담당자로 지정해드립니다

### 작업 방법
- 현재의 레포지터리를 자신의 깃허브로 포크
-  pre-kr-8.x 브랜치의 최상위 폴더에 있는 영문 파일의 내용을 kr 폴더 아래에 있는 문서로 복사후 번역
    -  최상위 폴더에 있는 파일은 수정하지 않습니다.
    -  kr 폴더 아래에 있는 파일을 수정합니다
    - 기존 문서를 참고하여 작업합니다

###
- 번역 신청 마감 : 1월 31일
- 번역 마감 : 2월 14일
- 문서 출시일 : 2월 28일 

### 번역 문서
- [x] artisan.md @AcidF0x
- [x] authentication.md @shaul1991
- [x] authorization.md @shaul1991
- [x] billing.md @dhtmdgkr123
- [x] blade.md @kkame
- [x] broadcasting.md
- [x] cache.md
- [x] cashier-paddle.md @Mo-zang
- [x] collections.md @HeuJung
- [x] configuration.md @Mo-zac
- [x] console-tests.md @KDudoo -> @kkame
- [x] container.md @JeongmyeongzZ
- [x] contracts.md @findstar
- [x] contributions.md
- [x] controllers.md @N0FreeLunch
- [x] csrf.md @Laeng
- [x] database-testing.md
- [x] database.md
- [x] deployment.md @gommmm
- [x] documentation.md @Kyungseo-Park
- [x] dusk.md
- [x] eloquent-collections.md @Mo-zac
- [x] eloquent-mutators.md @Kyungseo-Park
- [x] eloquent-relationships.md @findstar
- [x] eloquent-resources.md @Kyungseo-Park
- [x] eloquent-serialization.md @Kyungseo-Park
- [x] eloquent.md @Kyungseo-Park
- [x] encryption.md
- [x] envoy.md
- [x] errors.md @N0FreeLunch
- [x] events.md @findstar
- [x] facades.md
- [x] filesystem.md @DongHoWon
- [x] fortify.md @SilNex
- [x] hashing.md @N0FreeLunch
- [x] helpers.md @ongyjho
- [x] homestead.md
- [x] horizon.md 
- [x] http-client.md @HeuJung
- [x] http-tests.md @KDudoo -> @kkame
- [x] installation.md @gommmm
- [x] license.md
- [x] lifecycle.md @JeongJaeSoon -> @kkame
- [x] localization.md
- [x] logging.md
- [x] mail.md @Kyungseo-Park 
- [x] middleware.md @findstar
- [x] migrations.md @corean
- [x] mix.md @N0FreeLunch
- [x] mocking.md @wonjun3991
- [x] notifications.md @evans-kim
- [x] octane.md @truekim819 
- [x] packages.md @truekim819 -> @kkame
- [x] pagination.md @corean
- [x] passport.md @Kyungseo-Park
- [x] passwords.md @N0FreeLunch
- [x] providers.md @truekim819 -> @kkame
- [x] queries.md @AcidF0x
- [x] queues.md @AcidF0x -> @kkame
- [x] rate-limiting.md @SilNex
- [x] readme.md
- [x] redirects.md @N0FreeLunch
- [x] redis.md @castell9000
- [x] releases.md @findstar 
- [x] requests.md @truekim819 
- [x] responses.md @truekim819 -> @kkame
- [x] routing.md @findstar
- [x] sail.md @castell9000
- [x] sanctum.md @DongHoWon
- [x] scheduling.md @yunh03
- [x] scout.md @findstar
- [x] seeding.md @corean -> @kkame
- [x] session.md @DongHoWon
- [x] socialite.md @wonjun3991
- [x] starter-kits.md @Laeng
- [x] structure.md @findstar
- [x] telescope.md @Kyungseo-Park 
- [x] testing.md @yunh03
- [x] upgrade.md @findstar
- [x] urls.md @Ihyun
- [x] valet.md @JeongJaeSoon -> @kkame
- [x] validation.md @JeongJaeSoon -> @kkame
- [x] verification.md @1ocate
- [x] views.md @shaul1991

**Comment by shaul1991** [comment]
authentication.md
authorization.md

신청합니다

**Comment by wonjun3991** [comment]
socialite.md
mocking.md
신청합니다.

**Comment by castell9000** [comment]
sail.md
redis.md
신청합니다

**Comment by findstar** [comment]
upgrade.md 
신청합니다.

**Comment by 1ocate** [comment]
verification.md 
신청합니다.

**Comment by Mo-zang** [comment]
eloquent-collections.md
configuration.md
신청합니다.

**Comment by HeuJung** [comment]
collections.md
http-client.md
신청합니다.

**Comment by gommmm** [comment]
deployment.md
installation.md
신청합니다.

**Comment by aihoshistar** [comment]
eloquent-mutators.md

 eloquent-resources.md
 eloquent-serialization.md
 eloquent.md

신청합니다

다른 분들이 eloquent 부분에서 하고 싶은 부분이 있다면 빼도록 하겠습니다

**Comment by truekim819** [comment]
octane.md

packages.md

providers.md

requests.md

responses.md

신청합니다 :)

**Comment by dhtmdgkr123** [comment]
billing.md 신청합니다~

**Comment by DongHoWon** [comment]
filesystem.md
sanctum.md
신청합니다 ~~

**Comment by kkame** [comment]
금일 문서 최신화 작업을 완료하였습니다.

혹시 먼저 시작하신 분은 지금 문서를 기준으로 시작해주세요

감사합니다

**Comment by JeongJaeSoon** [comment]
안녕하세요! 까메님

 lifecycle.md
 valet.md
 validation.md
 
 신청합니다!!

**Comment by N0FreeLunch** [comment]
controllers.md
errors.md
hashing.md

신청합니다.

**Comment by JeongmyeongzZ** [comment]
container.md

신청합니다. ㅎㅎ 개인 블로그나 혼자 이것저것 번역을 하던게 있는데 벌써 다 뺐겼네여 😂

**Comment by Ihyun** [comment]
urls.md

신청합니다.

**Comment by ongyjho** [comment]
helpers.md

신청합니다!

**Comment by corean** [comment]
migrations.md

신청합니다.

**Comment by yunh03** [comment]
testing.md
scheduling.md
readme.md

신청합니다.

**Comment by kkame** [comment]
@yunh03 readme.md 파일은 의도적으로 번역하지 않고 있습니다. 제가 따로 표시를 안해드려서 오해를 드렸네요.

이 파일은 빼고 번역자로 추가해두었습니다. 신청해주셔서 감사합니다

**Comment by Laeng** [comment]
csrf.md
starter-kits.md

신청합니다!

**Comment by KDudoo** [comment]
console-tests.md
http-tests.md 신청 합니다~

**Comment by 0xFoxTail** [comment]
queries.md
queues.md
artisan.md
신청합니다

**Comment by findstar** [comment]
contracts
eloquent-relationships
events
routing
middleware
scout
structure
신청합니다.

**Comment by silnex** [comment]
rate-limiting
fortify

신청합니다.

**Comment by kkame** [comment]
blade 
신청합니다

**Comment by kkame** [comment]
https://docs.google.com/presentation/d/1lahARUYY6C4_z8RFl7W-GTFNG8kJYvBzd2rY-g1hhv4/edit?usp=sharing

혹시 작업하시면서 헷갈리는게 있는 분들은 이 문서 한번 보시면 좋을 것 같습니다

**Comment by corean** [comment]
pagination
seeding : 기번역되어 있네요
신청합니다

**Comment by shaul1991** [comment]
views.md 신청합니다.

**Comment by DongHoWon** [comment]
database-testing.md 신청합니다.

**Comment by Mo-zang** [comment]
cashier-paddle.md 추가 번역 신청합니다.

**Comment by DongHoWon** [comment]
session.md 신청합니다.

**Comment by findstar** [comment]
releases.md 추가 번역 신청합니다.

**Comment by N0FreeLunch** [comment]
mix.md
redirects.md
passwords.md
추가 번역 신청 합니다.

**Comment by aihoshistar** [comment]
documentation.md
추가 번역 신청 합니다.

**Comment by aihoshistar** [comment]
mail.md
telescope.md

추가 번역 신청 합니다.

**Comment by evans-kim** [comment]
notification.md
신청합니다

**Comment by aihoshistar** [comment]
passport.md

추가 번역 신청 합니다.
(불금이니까)

**Comment by kkame** [comment]
안녕하세요! 
다들 바쁘신 와중에도 번역에 참가해주셔서 번역이 많이 진행되었습니다.

사전에 신청해주신 문서외에는 모두 번역이 마무리되어 20일까지 신청자분들의 번역을 최종 마감할 예정입니다

만약 20일보다 조금 더 시간이 필요하신 분들은 댓글이나 저에게 개별로 연락을 부탁드립니다

21일부터는 기존에 할당된 문서들도 제가 번역을 진행하여 

이번달 말까지 최종 한글 편집까지 끝낸 후 2월27일 8.x 문서 최신화 작업을 마무리 할 예정입니다.


3월 1일부터는 9.x 번역을 진행 할 예정이니 그때도 많은 참여 부탁드리겠습니다.

9.x 번역에 대해서는 추후에 다시 공지를 올리도록 하겠습니다. 

ps. 모던퍼그 디스코드나, 라라벨 공홈에 번역자로 등록되지 않은 분들이 있다면 저에게 알려주세요. 

참여해주셔서 감사합니다.

**Comment by kkame** [comment]
예상보다 남은 문서분량이 많아 작업이 조금 더 길어질 것 같습니다. 8.x문서 출시 및 9.x 번역 시작은 1~2주 가량 연기 될 예정입니다.

**Comment by kkame** [comment]
번역이 모두 마무리되어 현재 홈페이지에 최종 반영완료하였습니다. 참여해주셔서 감사합니다!
