### ISSUE TITLE
[9.x] 문서 감수

### ISSUE THREAD

**Issue by kkame** [laravelkr/docs#436]
### 참여방법
- 댓글로 참여를 원하시는 문서를 코멘트로 남겨 주시면 해당 문서의 담당자로 지정해드립니다

### 작업 방법
- 현재의 레포지터리를 자신의 깃허브로 포크
- kr 폴더내에 있는 신청한 파일의 번역내용 감수
  - 수정이 필요한 부분만 변경하여 PR
  - 수정이 필요 없을 경우 이 이슈의 코멘트에 `xxx 파일 감수완료` 로 코멘트

### 감수 방법에 대한 짧은 가이드
- kr 폴더내의 문서와 영문 문서를 diff 한 뒤에 추가된 한글 이외에 
  - 잘못 변경되거나
  - 한글 번역이 누락된 부분이 있는지 확인
- kr 번역 문서의 문맥이 맞지 않는 부분이 있다면 변경하여 PR 

###
- 신청 마감 : 3월 31일까지
- 감수 마감 : 3월 31일까지
- 문서 출시일 : 4월 3일 

승인된 분들은 바로 감수에 들어가시면 됩니다.
감수 마감이 신청마감과 동일한 이유는 중간 신청은 얼마든지 가능하지만 마감일은 동일하게 하겠다라는 의미 입니다.
31일을 기준으로 모든 감수는 종료되고 문서 출시 이후에는 자유롭게 PR 주시면 됩니다

### 감수 문서
- [ ] artisan.md
- [ ] authentication.md
- [ ] authorization.md
- [ ] billing.md
- [ ] blade.md @N0FreeLunch
- [ ] broadcasting.md
- [ ] cache.md
- [ ] cashier-paddle.md
- [ ] collections.md
- [ ] configuration.md
- [ ] console-tests.md
- [ ] container.md
- [ ] contracts.md
- [ ] contributions.md
- [ ] controllers.md @N0FreeLunch
- [ ] csrf.md
- [ ] database-testing.md
- [ ] database.md @Mo-zang
- [ ] deployment.md
- [ ] documentation.md
- [ ] dusk.md
- [ ] eloquent-collections.md
- [ ] eloquent-mutators.md @N0FreeLunch
- [ ] eloquent-relationships.md @Mo-zang
- [ ] eloquent-resources.md
- [ ] eloquent-serialization.md
- [ ] eloquent.md
- [ ] encryption.md
- [ ] envoy.md
- [ ] errors.md @N0FreeLunch
- [ ] events.md
- [ ] facades.md
- [ ] filesystem.md
- [ ] fortify.md
- [ ] hashing.md @N0FreeLunch
- [ ] helpers.md
- [ ] homestead.md
- [ ] horizon.md
- [ ] http-client.md
- [ ] http-tests.md
- [ ] installation.md
- [ ] license.md
- [ ] lifecycle.md @JeongmyeongzZ
- [ ] localization.md
- [ ] logging.md
- [ ] mail.md
- [ ] middleware.md @N0FreeLunch
- [ ] migrations.md @N0FreeLunch
- [ ] mix.md @N0FreeLunch
- [ ] mocking.md @wonjun3991
- [ ] notifications.md
- [ ] octane.md
- [ ] packages.md
- [ ] pagination.md
- [ ] passport.md
- [ ] passwords.md @N0FreeLunch
- [ ] providers.md @JeongmyeongzZ
- [ ] queries.md
- [ ] queues.md @N0FreeLunch
- [ ] rate-limiting.md
- [ ] readme.md
- [ ] redirects.md @N0FreeLunch
- [ ] redis.md
- [ ] releases.md
- [ ] requests.md @Mo-zang
- [ ] responses.md
- [ ] routing.md
- [ ] sail.md
- [ ] sanctum.md @N0FreeLunch
- [ ] scheduling.md
- [ ] scout.md
- [ ] seeding.md
- [ ] session.md
- [ ] socialite.md @wonjun3991
- [ ] starter-kits.md
- [ ] structure.md
- [ ] telescope.md
- [ ] testing.md
- [ ] upgrade.md
- [ ] urls.md
- [ ] valet.md
- [ ] validation.md
- [ ] verification.md
- [ ] views.md

**Comment by wonjun3991** [comment]
mocking.md
socialite.md 
신청합니다

**Comment by Mo-zang** [comment]
eloquent-relationships.md
database.md
requests.md
신청합니다

**Comment by N0FreeLunch** [comment]
controllers.md
errors.md
hashing.md
mix.md
passwords.md
redirects.md

신청합니다.

**Comment by JeongmyeongzZ** [comment]
lifecycle.md
 providers.md

신청합니다.

**Comment by N0FreeLunch** [comment]
blade.md
sanctum.md
queues.md
middleware.md
migrations.md
eloquent-mutators.md
검토 신청합니다.

**Comment by kkame** [comment]
참여해주신 덕분에 검수를 빠르게 마무리해 문서를 하루 일찍 출시하였습니다. 참여해주신 분들 모두 감사합니다!
