### ISSUE TITLE
[9.x] Valet 제목 - 영문이 뜨는 이슈 

### ISSUE THREAD

**Issue by sunsilver** [laravelkr/docs#442]
### 대상 버전
9.x

### 요청사항
 - 사용자 페이지에 아래 이미지처럼 출력됩니다. 

![image](https://user-images.githubusercontent.com/44830861/164222776-58a58aaf-0a66-4672-98c3-e301be4487ea.png)

https://laravel.kr/docs/9.x/valet#The%20%3Ccode%3EfrontControllerPath%3C/code%3E%20Method 

### 참고사항
https://github.com/laravelkr/docs/blob/pre-kr-9.x/kr/valet.md 를 봤더니 문제가 없어 보여요 
왜 이런걸까요?

**Comment by kkame** [comment]
안녕하세요 @sunsilver 님

말씀하신 부분은 pre-kr-9.x 브랜치의 파일을 수정하여 kr-9.x로 최종 완성본으로 편집하는 과정사이에서 실수로 발생한 부분이라
확인하고 수정 완료했습니다
제보 감사드립니다


@all-contributors please add @sunsilver for doc
